name: Rust-wasm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.3.0
      #with:
        # Optional version of wasm-pack to install (eg. "v0.9.1", "latest")
        #version: # optional, default is latest
    - name: Install GUI dependencies
      run: sudo apt update && sudo apt install -y librust-glib-dev librust-pangocairo-dev librust-atk-dev librust-gdk-sys-dev
    - name: Rust check
      run: cargo c
    - name: Run Rust tests
      run: cargo test --verbose
    # wasm-bindgen demands crate-type = ["cdylib", "rlib"], but it will break trunk.
    # - name: Build
    #   run: cd gui && wasm-pack build --target web

    - uses: jetli/trunk-action@v0.4.0
      with:
        # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
        version: 'latest'
    - name: Build with trunk
      run: rustup target add wasm32-unknown-unknown && cd gui && RUSTFLAGS='--cfg=web_sys_unstable_apis' trunk build --release
    - name: Check artifacts
      run: cd gui && ls dist
